---

- name: Create the directory for ldap database
  file: path=/var/lib/ldap/{{ openldap_server_domain_name }}/ state=directory owner={{ openldap_server_user }} group={{ openldap_server_user }}

- name: start the slapd service
  service: name=slapd state=started enabled=yes

- name: Copy the template for creating base dn
  template: src=domain.ldif.j2 dest={{ openldap_server_app_path }}/domain.ldif
  register: domain_copy

- name: we should restart slapd before adding creating new domain
  meta: flush_handlers

- name: add the base domain
  when: domain_copy.changed
  register: command_result
  failed_when: "command_result.rc not in [0,68]"
  shell: ldapadd -c -x -D "{{ openldap_server_rootdn }}" -w {{ openldap_server_rootpw }} -f {{ openldap_server_app_path }}/domain.ldif
