---

- name: Install the openldap and required packages
  package:
    name:
      - slapd
      - ldap-utils
      - python-selinux
      - openssl
    state: present

- name: Delete the configuration directory
  file: path={{ openldap_server_app_path }}/slapd.d state=absent

- name: Generate the root password for ldap
  shell: slappasswd -h {"{{ openldap_server_hashing}}"} -s {{ openldap_server_rootpw }}
  changed_when: False
  register: root_password

- name: copy openssh-ldap schema
  copy: src=openssh-ldap.schema dest="{{ openldap_server_app_path }}/schema/openssh-ldap.schema"
  notify:
   - restart slapd

- name: copy vsh-access-control schema
  copy: src=vsh-access-control.schema dest="{{ openldap_server_app_path }}/schema/vsh-access-control.schema"
  notify:
   - restart slapd

- name: copy vsh-messenger schema
  copy: src=vsh-messenger.schema dest="{{ openldap_server_app_path }}/schema/vsh-messenger.schema"
  notify:
   - restart slapd

- name: Copy the slapd.conf configuration file
  template: src=slapd.conf.j2 dest={{ openldap_server_app_path }}/slapd.conf
  notify:
   - restart slapd

- name: Copy the acl configuration file
  template: src=acl.conf.j2 dest={{ openldap_server_app_path}}/acl.conf
  notify:
    - restart slapd

- name: Copy the ldap.conf configuration file
  template: src=ldap.conf.j2 dest={{ openldap_server_app_path }}/ldap.conf
