---
  - name: install molly-guard
    apt: name=molly-guard state=latest update_cache=yes
    tags: packages

  - name: configure molly-guard
    copy: dest=/etc/molly-guard/rc
          src=molly-guard/rc
          owner=root group=root mode=0644
